"""Initial local data schema

Revision ID: 2459c63d8fb5
Revises: none
Create Date: 2026-10-04 08:47:38.879205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2459c63d8fb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlb_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('resource_key', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'resource_key', name='uq_mlb_payload_resource')
    )
    op.create_table('players',
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('mlb_id')
    )
    op.create_table('profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_kind', sa.String(length=16), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('split_key', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('through_date', sa.Date(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_kind', 'player_id', 'split_key', 'model_version', 'through_date', name='uq_profile_snapshot')
    )
    op.create_table('statcast_pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_number', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('hitter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_hand', sa.String(length=1), nullable=False),
    sa.Column('batter_side', sa.String(length=1), nullable=False),
    sa.Column('pitch_type', sa.String(length=8), nullable=False),
    sa.Column('velocity_mph', sa.Float(), nullable=True),
    sa.Column('horizontal_movement_ft', sa.Float(), nullable=True),
    sa.Column('vertical_movement_ft', sa.Float(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('plate_x_ft', sa.Float(), nullable=True),
    sa.Column('plate_z_ft', sa.Float(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=True),
    sa.Column('exit_velocity_mph', sa.Float(), nullable=True),
    sa.Column('launch_angle_deg', sa.Float(), nullable=True),
    sa.Column('estimated_woba', sa.Float(), nullable=True),
    sa.Column('woba_value', sa.Float(), nullable=True),
    sa.Column('woba_denominator', sa.Float(), nullable=True),
    sa.Column('launch_speed_angle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'at_bat_number', 'pitch_number', name='uq_statcast_pitch_identity')
    )
    op.create_index(op.f('ix_statcast_pitches_game_date'), 'statcast_pitches', ['game_date'], unique=False)
    op.create_index(op.f('ix_statcast_pitches_hitter_id'), 'statcast_pitches', ['hitter_id'], unique=False)
    op.create_index(op.f('ix_statcast_pitches_pitcher_id'), 'statcast_pitches', ['pitcher_id'], unique=False)
    op.create_table('teams',
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('mlb_id')
    )
    op.create_table('games',
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.mlb_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.mlb_id'], ),
    sa.PrimaryKeyConstraint('mlb_id')
    )
    op.create_table('appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.mlb_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.mlb_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.mlb_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'role', name='uq_appearance_player_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appearances')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_index(op.f('ix_statcast_pitches_pitcher_id'), table_name='statcast_pitches')
    op.drop_index(op.f('ix_statcast_pitches_hitter_id'), table_name='statcast_pitches')
    op.drop_index(op.f('ix_statcast_pitches_game_date'), table_name='statcast_pitches')
    op.drop_table('statcast_pitches')
    op.drop_table('profile_snapshots')
    op.drop_table('players')
    op.drop_table('mlb_payloads')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
