"""Add extensible Statcast source fields

Revision ID: b48b64a70120
Revises: 2459c63d8fb5
Create Date: 2026-10-04 08:51:51.994332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48b64a70120'
down_revision: Union[str, Sequence[str], None] = '2459c63d8fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_pitches', sa.Column('source_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_pitches', 'source_fields')
    # ### end Alembic commands ###
